# yolov8_config.yaml
train: /mnt/c/My_files/Study/ForVectorBest2/YOLO_dataset/train/images  # Путь к изображениям для тренировки
val: /mnt/c/My_files/Study/ForVectorBest2/YOLO_dataset/valid/images    # Путь к изображениям для валидации
test: /mnt/c/My_files/Study/ForVectorBest2/YOLO_dataset/test/images    # Путь к изображениям для тестирования

# Путь к файлам с аннотациями
train_labels: /mnt/c/My_files/Study/ForVectorBest2/YOLO_dataset/train/labels
val_labels: /mnt/c/My_files/Study/ForVectorBest2/YOLO_dataset/valid/labels
test_labels: /mnt/c/My_files/Study/ForVectorBest2/YOLO_dataset/test/labels   # Путь к аннотациям для тестовых данных

# Классы
nc: 1  # Количество классов
names: ['sticker']  # Ваши классы
